// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID        string `json:"_id" bson:"_id"`
	Name      string `json:"name"`
	Birthdate string `json:"birthdate"`
}

type AuthorInput struct {
	Name      string `json:"name"`
	Birthdate string `json:"birthdate"`
}

type Book struct {
	ID     string  `json:"_id" bson:"_id"`
	Title  string  `json:"title"`
	Author *Author `json:"author"`
}

type BookInput struct {
	Title string `json:"title"`
}
